### ISSUE TITLE
Clonotyme usage

### ISSUE THREAD

**Issue by leeanapeters** [alexyermanos/Platypus#11]
Hi all, 

I am very interested in using the clonotyme functionality with my data, but haven't seen an example in the vignettes for usage. 

Would this be possible to add? Or would you be able to provide some guidance on applying it to my data?

Appreciate your help!

Leeana

**Comment by alexyermanos** [comment]
We are working on a vignette/walk through for this currently and will post it on the website when ready. sorry for the delay - this was initially included in the package but removed to due to reviewer comments. I will organize some of the code that we have used though for the analysis and provide it to you

**Comment by leeanapeters** [comment]
Thank you, I really appreciate it!

If you'd rather send by email that is fine too, you can reach me at leeanapeters@ufl.edu
