### ISSUE TITLE
how to add both vdj_B and vdj_T same time

### ISSUE THREAD

**Issue by Lei-GitHub** [alexyermanos/Platypus#34]
Hi,
I want to try the method VDJ_GEX_matrix, I have vdj_b and vdj_t, GEX and feature antibodies. Can I call VDJ_GEX_matrix same time, How to do that? I see the parameter VDJ.out.directory.list, Is that I only can add one VDJ data to VDJ_GEX_matrix function? Thank you very much.
Best,
Lei

**Comment by vickreiner** [comment]
Hi Lei,

the VGM function can handle input from both B and T reperoires in the same run and compile a common matrix. 
We do not recommend this though, because following analysis functions (e.g. clonotyping, abundances) are not build to run B and T repertoires in the same call. 

You can run the VGM twice, providing the same GEX and Feature Barcode input directories and changing only the VDJ input directories to include only T or B cells. 
The VDJ.out.directory.list lets you add as many Cellranger VDJ output directories as you wish. 
Hope this helps, please let us know if you encounter any issues!
