### ISSUE TITLE
VDJ_Dynamics not recognizing feature column

### ISSUE THREAD

**Issue by LBH2021** [alexyermanos/Platypus#35]
When I try to perform VDJ dynamics, I get the following error message (script and error message below). When I check the data frame columns, the designated column is present, and other repertoire dynamics functions such as VDJ_abundances and VDJ_ordination work using the same column.to.track input. Any help would be greatly appreciated. Thank you!

> ###Tracks shared VDJ and VJ features across samples
>       VDJ_dynamics(VDJ = TestVGM, 
+                    columns.to.track = 'VDJ_cdr3s_aa', #select which column in dataframe to track
+                    timepoints.column = 'sample_id',
+                    proportions.level = 'absolute.counts',
+                    track.only.common = T)
Error in VDJ_dynamics(VDJ = TestVGM, columns.to.track = "VDJ_cdr3s_aa",  : 
  Please provide valid feature column name(s) contained within VDJ

**Comment by tudorcotet** [comment]
Hi! Sorry for the late reply! 

The VDJ_dynamics takes as input the VDJ part of the VGM object - VGM[[1]]. The error above is most likely due to having the whole VGM object as input, instead of the VDJ. Calling VDJ_dynamics with VDJ = TestVGM[[1]] should fix your issue!

We are planning to standardize the inputs for all Platypus functions to be the VGM object!
